### ISSUE TITLE
Support Parameters for middlewares initialization

### ISSUE THREAD

**Issue by thiagobustamante** [Leanty/tree-gateway#12]
Support inform parameters for middlewares.

Something like:

```yml
proxy:
  target:
    host: http://httpbin.org
  filter:
  - middleware:
      name: myBlacklistFilter
      options: 
          - 10.100.144.35
          - 8.8.8.8
  - middleware:
      name: mySecondFilter
```
