### ISSUE TITLE
'OR' support in a Group path condition

### ISSUE THREAD

**Issue by geldoronie** [Leanty/tree-gateway#138]
Implement a OR support in a group path condition for the API's, today the implementation uses a AND condition where impossible make the follow Example:

```
group:
    -
        id: FreeGroup
        member:
            -
                method:
                    - POST
                    - OPTIONS
                    - GET
                protocol:
                    - http
                path:
                    - '!**/auth'
                    - '!**/set-new-password'
                    - '!**/ask-new-password-code'
```
To Work around this problem is possible to use the same routes but placing it inside a grouped path:

```
group:
    -
        id: FreeGroup
        member:
            -
                method:
                    - POST
                    - OPTIONS
                    - GET
                protocol:
                    - http
                path:
                    - '!**/freeroutes'
```
