### ISSUE TITLE
Some examples of monitoring please.

### ISSUE THREAD

**Issue by sanguohot** [Leanty/tree-gateway#152]
Could not found in any docs.
Any help from you will be greatly appreciated.

**Comment by thiagobustamante** [comment]
Hi @sanguohot ,

It is possible to use any custom middleware to handle how your analytics data should be processed.

Tree gateway already includes a middleware that collect the log entries and store them into the redis database.

I recommend you to use this middleware and then configure logstash to collect from redis and send to your log server (I use elasticsearch).

To enable the redis middleware for the logs, just configure your gateway:

```yaml
gateway:
    analytics:
        enabled: true
        logger:
            name: redis
```
You can found the docs [here](https://github.com/Leanty/tree-gateway/wiki/gatewayconfig#requestanalyticsconfig).
