### ISSUE TITLE
Treegateway add '/ ' to GET request trigerring 404 not found error

### ISSUE THREAD

**Issue by tfoutrein** [Leanty/tree-gateway#156]
When i'm trying to use a simple API like this 

```yaml
name: chappie-tts
version: 0.1.0
path: chappie/tts
proxy:
    target:
        host: 'https://gateway_url/ms_chappie/api/readings'
```

there is a pb when calling `chappie/tts?text=bonjour&audio_format=mp3` the service receive the request like this : 
`https://gateway_url/ms_chappie/api/readings/?ext=bonjour&audio_format=mp3`

i think it's an issue, or perhaps if i've misunderstood the api 

Thank you in advance
