### ISSUE TITLE
Support for hostname matching

### ISSUE THREAD

**Issue by fabsrc** [Leanty/tree-gateway#96]
When multiple domains point to the gateway it would be nice to be able to use different APIs and/or paths for them. E.g. `api.example.com` should proxy all incoming requests to `http://httpbin.org` while `docs.example.com` should proxy all incoming requests to `https://requestb.in/1f1ww8l1`.
This should be possible by using a single hostname, a list of hostnames or a wildcard/regex syntax.

For comparison here is the API configuration documentation for [express-gateway](https://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints#host) and [kong](https://getkong.org/docs/0.12.x/admin-api/#add-api) where this feature is already supported.

The ExpressJS [vhost](https://github.com/expressjs/vhost) module can be used to implement this feature.

**Comment by thiagobustamante** [comment]
Hi,

We can configure this scenario in tree-gateway through a [Router middleware](https://github.com/Leanty/tree-gateway/wiki/Proxy#proxyrouter).

Proxy Router is a kind of middleware that can be used to change how the request pipeline will handle your requests. You can define your own middleware function or use one of the [already included middlewares](https://github.com/Leanty/tree-gateway/wiki/Routing-Middlewares#proxy-routers).

To route something based on the host header, you could configure something like:

```yaml
---
name: MyAPI
version: 1.0.0
path: "/myapi"
proxy:
  target:
    router:
      middleware:
        name: header
        options:
          name: host
          defaultTarget: http://httpbin.org
          destinations: 
            - target: http://httpbin.org
              value: api.example.com
            - target: https://requestb.in/1f1ww8l1
              value: docs.example.com
```

In this example, I am using [this](https://github.com/Leanty/tree-gateway/wiki/header) middleware, included in the default distribution. It is a simple middleware that can not handle expressions like *.example.com (like vhost that you suggested).

I want to say that I really like the suggestion to support expressions like that and I will add this feature to the next release.
